name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: miscellaneous.azurecr.io
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t miscellaneous.azurecr.io/hacknights-app:latest .

    - name: Push Docker image
      run: |
        docker push miscellaneous.azurecr.io/hacknights-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Web App Deploy
      uses: Azure/webapps-deploy@v2
      with:
        app-name: hacknights
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: 'miscellaneous.azurecr.io/hacknights-app:latest'
